name: gradleCI

on:  
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Add exec permission
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build
    - name: Upload Lint report
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: lint-results.html
        path: app/build/reports/lint-results.html
