name: Publish package to GitHub Packages
on: [push, workflow_dispatch]
jobs:
  publish:
    #if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
          check-latest: true
      - name: Add exec permission
        run: chmod +x gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}